bindAddr = "0.0.0.0"
bindPort = 7100
kcpBindPort = 7100

webServer.addr = "0.0.0.0"
webServer.port = 7500
webServer.user = ""
webServer.password = ""


log.to = "/frpslog/frps.log"
log.level = "info"
log.maxDays = 3

auth.method = "token"
auth.token = "tokentoken"

allowPorts = [
{ start = 6000, end = 7000},
]
